// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShatteredRealms.Infrastructure.Data;

#nullable disable

namespace ShatteredRealms.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227182024_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmergencyContact", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("ForumCategory", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.ForumPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ThreadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ForumPost", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.ForumThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ForumThread", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.ViewOwn",
                            Description = "View own profile",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 102,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.UpdateOwn",
                            Description = "Update own profile",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 103,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.View",
                            Description = "View any user",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 104,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.Create",
                            Description = "Create users",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 105,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.Update",
                            Description = "Update any user",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 106,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.Delete",
                            Description = "Delete users",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 107,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.ViewOwn",
                            Description = "View own characters",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 108,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.CreateOwn",
                            Description = "Create own characters",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 109,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.UpdateOwnBasic",
                            Description = "Update own character name/nation",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 110,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.View",
                            Description = "View any character",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 111,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.Update",
                            Description = "Update any character",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 112,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.Delete",
                            Description = "Delete any character",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 113,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.AssignPosition",
                            Description = "Assign societal/military position",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 114,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.AssignExperience",
                            Description = "Assign experience/level",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 115,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.View",
                            Description = "View roles",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 116,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.Create",
                            Description = "Create roles",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 117,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.Update",
                            Description = "Update roles",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 118,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.Delete",
                            Description = "Delete roles",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 119,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.Assign",
                            Description = "Assign roles to users",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 120,
                            Category = "PermissionControl",
                            ClaimType = "permission",
                            ClaimValue = "PermissionControl.View",
                            Description = "View permissions",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 121,
                            Category = "PermissionControl",
                            ClaimType = "permission",
                            ClaimValue = "PermissionControl.Assign",
                            Description = "Assign permissions to roles",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 122,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.category.create",
                            Description = "Create forum categories",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 123,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.category.edit",
                            Description = "Update forum categories",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 124,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.category.delete",
                            Description = "Delete forum categories",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 125,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.create",
                            Description = "Create forum threads",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 126,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.update",
                            Description = "Update any forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 127,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.delete",
                            Description = "Delete any forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 128,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.lock",
                            Description = "Lock/unlock forum threads",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 129,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.pin",
                            Description = "Pin/unpin forum threads",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 130,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.create",
                            Description = "Create posts in threads",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 131,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.edit",
                            Description = "Update any forum post",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 132,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.delete",
                            Description = "Delete any forum post",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 133,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.updateOwn",
                            Description = "Update own forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 134,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.deleteOwn",
                            Description = "Delete own forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 135,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.editOwn",
                            Description = "Update own forum post",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 136,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.deleteOwn",
                            Description = "Delete own forum post",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 137,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.create",
                            Description = "Create wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 138,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.edit",
                            Description = "Update any wiki page",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 139,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.editOwn",
                            Description = "Update any wiki page",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 140,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.delete",
                            Description = "Delete wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 141,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.deleteOwn",
                            Description = "Delete own wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 142,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.category.manage",
                            Description = "Create/update wiki categories",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 201,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.ViewOwn",
                            Description = "View own profile",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 202,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.UpdateOwn",
                            Description = "Update own profile",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 203,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.View",
                            Description = "View any user",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 204,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.Create",
                            Description = "Create users",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 205,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.Update",
                            Description = "Update any user",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 206,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.Delete",
                            Description = "Delete users",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 207,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.ViewOwn",
                            Description = "View own characters",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 208,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.CreateOwn",
                            Description = "Create own characters",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 209,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.UpdateOwnBasic",
                            Description = "Update own character name/nation",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 210,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.View",
                            Description = "View any character",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 211,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.Update",
                            Description = "Update any character",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 212,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.Delete",
                            Description = "Delete any character",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 213,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.AssignPosition",
                            Description = "Assign societal/military position",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 214,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.AssignExperience",
                            Description = "Assign experience/level",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 215,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.View",
                            Description = "View roles",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 216,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.Create",
                            Description = "Create roles",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 217,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.Update",
                            Description = "Update roles",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 218,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.Delete",
                            Description = "Delete roles",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 219,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.Assign",
                            Description = "Assign roles to users",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 220,
                            Category = "PermissionControl",
                            ClaimType = "permission",
                            ClaimValue = "PermissionControl.View",
                            Description = "View permissions",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 221,
                            Category = "PermissionControl",
                            ClaimType = "permission",
                            ClaimValue = "PermissionControl.Assign",
                            Description = "Assign permissions to roles",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 222,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.category.create",
                            Description = "Create forum categories",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 223,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.category.edit",
                            Description = "Update forum categories",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 224,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.category.delete",
                            Description = "Delete forum categories",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 225,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.create",
                            Description = "Create forum threads",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 226,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.update",
                            Description = "Update any forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 227,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.delete",
                            Description = "Delete any forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 228,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.lock",
                            Description = "Lock/unlock forum threads",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 229,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.pin",
                            Description = "Pin/unpin forum threads",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 230,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.create",
                            Description = "Create posts in threads",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 231,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.edit",
                            Description = "Update any forum post",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 232,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.delete",
                            Description = "Delete any forum post",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 233,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.updateOwn",
                            Description = "Update own forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 234,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.deleteOwn",
                            Description = "Delete own forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 235,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.editOwn",
                            Description = "Update own forum post",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 236,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.deleteOwn",
                            Description = "Delete own forum post",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 237,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.create",
                            Description = "Create wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 238,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.edit",
                            Description = "Update any wiki page",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 239,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.editOwn",
                            Description = "Update any wiki page",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 240,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.delete",
                            Description = "Delete wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 241,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.deleteOwn",
                            Description = "Delete own wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 242,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.category.manage",
                            Description = "Create/update wiki categories",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 301,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.ViewOwn",
                            Description = "View own profile",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 302,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.UpdateOwn",
                            Description = "Update own profile",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 307,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.ViewOwn",
                            Description = "View own characters",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 308,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.CreateOwn",
                            Description = "Create own characters",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 309,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.UpdateOwnBasic",
                            Description = "Update own character name/nation",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 310,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.View",
                            Description = "View any character",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 311,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.Update",
                            Description = "Update any character",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 313,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.AssignPosition",
                            Description = "Assign societal/military position",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 314,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.AssignExperience",
                            Description = "Assign experience/level",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 315,
                            Category = "Role",
                            ClaimType = "permission",
                            ClaimValue = "Role.View",
                            Description = "View roles",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 320,
                            Category = "PermissionControl",
                            ClaimType = "permission",
                            ClaimValue = "PermissionControl.View",
                            Description = "View permissions",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 325,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.create",
                            Description = "Create forum threads",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 333,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.updateOwn",
                            Description = "Update own forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 334,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.deleteOwn",
                            Description = "Delete own forum thread",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 328,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.lock",
                            Description = "Lock/unlock forum threads",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 329,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.thread.pin",
                            Description = "Pin/unpin forum threads",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 330,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.create",
                            Description = "Create posts in threads",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 335,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.editOwn",
                            Description = "Update own forum post",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 336,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.deleteOwn",
                            Description = "Delete own forum post",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 337,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.create",
                            Description = "Create wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 339,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.editOwn",
                            Description = "Update any wiki page",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 341,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.deleteOwn",
                            Description = "Delete own wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 401,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.ViewOwn",
                            Description = "View own profile",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 402,
                            Category = "Users",
                            ClaimType = "permission",
                            ClaimValue = "Users.UpdateOwn",
                            Description = "Update own profile",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 407,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.ViewOwn",
                            Description = "View own characters",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 408,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.CreateOwn",
                            Description = "Create own characters",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 409,
                            Category = "Characters",
                            ClaimType = "permission",
                            ClaimValue = "Characters.UpdateOwnBasic",
                            Description = "Update own character name/nation",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 430,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.create",
                            Description = "Create posts in threads",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 435,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.editOwn",
                            Description = "Update own forum post",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 436,
                            Category = "Forum",
                            ClaimType = "permission",
                            ClaimValue = "forum.post.deleteOwn",
                            Description = "Delete own forum post",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 437,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.create",
                            Description = "Create wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 439,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.editOwn",
                            Description = "Update any wiki page",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 441,
                            Category = "Wiki",
                            ClaimType = "permission",
                            ClaimValue = "wiki.page.deleteOwn",
                            Description = "Delete own wiki pages",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        });
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            Description = "Internal system role, unrestricted",
                            IsSystem = true,
                            Name = "System",
                            NormalizedName = "SYSTEM",
                            Priority = 100
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            Description = "Full administrative access",
                            IsSystem = true,
                            Name = "Admin",
                            NormalizedName = "ADMIN",
                            Priority = 90
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            Description = "Can manage characters, assign positions/experience",
                            IsSystem = false,
                            Name = "EventOrganizer",
                            NormalizedName = "EVENTORGANIZER",
                            Priority = 50
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000004",
                            Description = "Standard registered user",
                            IsSystem = false,
                            Name = "User",
                            NormalizedName = "USER",
                            Priority = 10
                        });
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.UserEmergencyContact", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EmergencyContactId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "EmergencyContactId");

                    b.HasIndex("EmergencyContactId");

                    b.ToTable("UserEmergencyContact", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.WikiCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("WikiCategory", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.WikiPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("WikiPage", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.WikiPageCategory", b =>
                {
                    b.Property<int>("WikiPageId")
                        .HasColumnType("int");

                    b.Property<int>("WikiCategoryId")
                        .HasColumnType("int");

                    b.HasKey("WikiPageId", "WikiCategoryId");

                    b.HasIndex("WikiCategoryId");

                    b.ToTable("WikiPageCategory", (string)null);
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.WikiRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RevisionNote")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("WikiPageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EditorId");

                    b.HasIndex("WikiPageId");

                    b.ToTable("WikiRevision", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.ForumCategory", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.ForumPost", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShatteredRealms.Domain.Entities.ForumThread", "Thread")
                        .WithMany("Posts")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.ForumThread", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShatteredRealms.Domain.Entities.ForumCategory", "Category")
                        .WithMany("Threads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.Permission", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.UserEmergencyContact", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.EmergencyContact", "EmergencyContact")
                        .WithMany("UserEmergencyContact")
                        .HasForeignKey("EmergencyContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShatteredRealms.Domain.Entities.User", "User")
                        .WithMany("UserEmergencyContact")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmergencyContact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShatteredRealms.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.WikiPage", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.WikiPageCategory", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.WikiCategory", "Category")
                        .WithMany("Pages")
                        .HasForeignKey("WikiCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShatteredRealms.Domain.Entities.WikiPage", "Page")
                        .WithMany("Categories")
                        .HasForeignKey("WikiPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.WikiRevision", b =>
                {
                    b.HasOne("ShatteredRealms.Domain.Entities.User", "Editor")
                        .WithMany()
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShatteredRealms.Domain.Entities.WikiPage", "Page")
                        .WithMany("Revisions")
                        .HasForeignKey("WikiPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editor");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.EmergencyContact", b =>
                {
                    b.Navigation("UserEmergencyContact");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.ForumCategory", b =>
                {
                    b.Navigation("Threads");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.ForumThread", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserEmergencyContact");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.WikiCategory", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("ShatteredRealms.Domain.Entities.WikiPage", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
